---
services:
  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:0.11.0
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env.gateway
    depends_on:
      google-calendar-agent-healthcheck:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - a2a-network

  google-calendar-agent:
    build:
      context: ..
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - "8081:8080"
    env_file:
      - .env.agent
    restart: unless-stopped
    networks:
      - a2a-network

  a2a-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - client/.env
    depends_on:
      google-calendar-agent-healthcheck:
        condition: service_healthy
    networks:
      - a2a-network

  google-calendar-agent-healthcheck:
    image: curlimages/curl:latest
    entrypoint:
      - sh
      - -c
      - "while true; do sleep 30; done"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://google-calendar-agent:8080/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      google-calendar-agent:
        condition: service_started
    restart: unless-stopped
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge
