---
services:
  google-calendar-agent:
    build:
      context: ..
    env_file:
      - .env.agent
    restart: unless-stopped
    networks:
      - a2a-network

  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env.gateway
    restart: unless-stopped
    networks:
      - a2a-network

  cli:
    image: ghcr.io/inference-gateway/cli:latest
    pull_policy: always
    environment:
      INFER_LOGGING_DEBUG: true
      INFER_GATEWAY_URL: http://inference-gateway:8080
      INFER_A2A_ENABLED: true
      INFER_TOOLS_ENABLED: true
      INFER_TOOLS_QUERY_ENABLED: true
      INFER_TOOLS_TASK_ENABLED:  true
      INFER_AGENT_MODEL: deepseek/deepseek-chat
      INFER_A2A_AGENTS: 'http://google-calendar-agent:8080'
      INFER_A2A_CACHE_ENABLED: false
    command:
      - chat
    networks:
      - a2a-network
    profiles:
      - manual

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://google-calendar-agent:8080
    networks:
      - a2a-network
    profiles:
      - manual

networks:
  a2a-network:
    driver: bridge
