---
services:
  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env.gateway
    depends_on:
      google-calendar-agent-healthcheck:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - a2a-network

  google-calendar-agent:
    image: ghcr.io/inference-gateway/google-calendar-agent:latest
    pull_policy: always
    env_file:
      - .env.agent
    restart: unless-stopped
    networks:
      - a2a-network

  google-calendar-agent-healthcheck:
    image: curlimages/curl:latest
    entrypoint:
      - sh
      - -c
      - "while true; do sleep 30; done"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://google-calendar-agent:8080/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      google-calendar-agent:
        condition: service_started
    restart: unless-stopped
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --config
      - /config/.a2a.yaml
    command:
      - config
      - set
      - server-url
      - http://google-calendar-agent:8080
    volumes:
      - ./config:/config
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge
