apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: google-calendar-agent
  description: A Google Calendar A2A agent for AI assistants to interact with Google Calendar
  version: 0.4.17
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: false
  services:
    google:
      type: service
      interface: CalendarService
      factory: NewServiceFactory
      description: Google Calendar API service for managing calendar events
  skills:
    - id: list_calendar_events
      name: list_calendar_events
      description: List upcoming events from Google Calendar
      tags:
        - calendar
        - events
        - list
        - google
      schema:
        type: object
        properties:
          timeMin:
            type: string
            description: Start time (RFC3339 format, e.g., 2024-01-01T00:00:00Z). Defaults to now.
          timeMax:
            type: string
            description: End time (RFC3339 format, e.g., 2024-01-01T23:59:59Z). Optional.
          maxResults:
            type: integer
            description: "Maximum number of events to return (default: 10, max: 100)"
            minimum: 1
            maximum: 100
          query:
            type: string
            description: Free text search terms to find events. Optional.
      inject:
        - logger
        - google
    - id: create_calendar_event
      name: create_calendar_event
      description: Create a new event in Google Calendar
      tags:
        - calendar
        - events
        - create
        - google
      schema:
        type: object
        properties:
          summary:
            type: string
            description: Event title/summary (required)
          description:
            type: string
            description: Event description. Optional.
          startTime:
            type: string
            description: Start time in RFC3339 format (required, e.g., 2024-01-01T10:00:00Z)
          endTime:
            type: string
            description: End time in RFC3339 format (required, e.g., 2024-01-01T11:00:00Z)
          attendees:
            type: array
            items:
              type: string
            description: List of attendee email addresses. Optional.
          location:
            type: string
            description: Event location. Optional.
        required:
          - summary
          - startTime
          - endTime
      inject:
        - logger
        - google
    - id: update_calendar_event
      name: update_calendar_event
      description: Update an existing event in Google Calendar
      tags:
        - calendar
        - events
        - update
        - google
      schema:
        type: object
        properties:
          eventId:
            type: string
            description: Event ID to update (required)
          summary:
            type: string
            description: Event title/summary. Optional.
          description:
            type: string
            description: Event description. Optional.
          startTime:
            type: string
            description: Start time in RFC3339 format. Optional.
          endTime:
            type: string
            description: End time in RFC3339 format. Optional.
          location:
            type: string
            description: Event location. Optional.
        required:
          - eventId
      inject:
        - logger
        - google
    - id: delete_calendar_event
      name: delete_calendar_event
      description: Delete an event from Google Calendar
      tags:
        - calendar
        - events
        - delete
        - google
      schema:
        type: object
        properties:
          eventId:
            type: string
            description: Event ID to delete (required)
        required:
          - eventId
      inject:
        - logger
        - google
    - id: get_calendar_event
      name: get_calendar_event
      description: Get details of a specific event from Google Calendar
      tags:
        - calendar
        - events
        - get
        - google
      schema:
        type: object
        properties:
          eventId:
            type: string
            description: Event ID to retrieve (required)
        required:
          - eventId
      inject:
        - logger
        - google
    - id: find_available_time
      name: find_available_time
      description: Find available time slots in the calendar
      tags:
        - calendar
        - availability
        - scheduling
        - google
      schema:
        type: object
        properties:
          startDate:
            type: string
            description: Start date for search (RFC3339 format, e.g., 2024-01-01T00:00:00Z)
          endDate:
            type: string
            description: End date for search (RFC3339 format, e.g., 2024-01-01T23:59:59Z)
          duration:
            type: integer
            description: "Duration in minutes for the desired time slot (default: 60)"
            minimum: 15
            maximum: 480
        required:
          - startDate
          - endDate
      inject:
        - logger
        - google
    - id: check_conflicts
      name: check_conflicts
      description: Check for scheduling conflicts in the specified time range
      tags:
        - calendar
        - conflicts
        - scheduling
        - google
      schema:
        type: object
        properties:
          startTime:
            type: string
            description: Start time to check (RFC3339 format, required)
          endTime:
            type: string
            description: End time to check (RFC3339 format, required)
        required:
          - startTime
          - endTime
      inject:
        - logger
        - google
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are a Google Calendar AI agent specialized in calendar management and scheduling operations.

      Your primary capabilities:
      1. **Event Management**: Create, update, delete, and retrieve calendar events
      2. **Scheduling Intelligence**: Find available time slots and check for conflicts
      3. **Calendar Operations**: List events with flexible time ranges and search queries

      Key features:
      - Support for both mock mode (demo/testing) and production Google Calendar API
      - RFC3339 timestamp handling for accurate scheduling
      - Intelligent conflict detection and availability checking
      - Attendee management and location tracking
      - Comprehensive event search and filtering

      When helping users:
      - Always validate time formats and ranges
      - Provide clear feedback on scheduling conflicts
      - Suggest alternative time slots when conflicts are detected
      - Handle both simple and complex scheduling scenarios
      - Maintain data accuracy and consistency with Google Calendar

      Your responses should be accurate, helpful, and focused on calendar management tasks.
  config:
    google:
      serviceAccountJson: ""
      credentialsPath: ""
    googleCalendar:
      Id: "primary"
      mockMode: false
      timezone: "UTC"
  server:
    port: 8080
    debug: false
  language:
    go:
      module: github.com/inference-gateway/google-calendar-agent
      version: "1.25.0"
  acronyms:
    - a2a
    - api
    - rfc
    - json
    - yaml
  scm:
    provider: github
    url: https://github.com/inference-gateway/google-calendar-agent
    github_app: true
    issue_templates: true
  sandbox:
    flox:
      enabled: true
