FROM alpine:latest AS builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN apk add --no-cache upx
COPY google-calendar-agent /artifacts/agent
RUN upx --best --lzma /artifacts/agent

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /artifacts/agent /google-calendar-agent
COPY .well-known/agent.json .well-known/agent.json
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/google-calendar-agent"]
