// Code generated by ADL CLI v0.54.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	envconfig "github.com/sethvargo/go-envconfig"
	cobra "github.com/spf13/cobra"
	zap "go.uber.org/zap"
	yaml "gopkg.in/yaml.v3"

	server "github.com/inference-gateway/adk/server"

	config "github.com/inference-gateway/google-calendar-agent/config"
	tools "github.com/inference-gateway/google-calendar-agent/tools"

	google "github.com/inference-gateway/google-calendar-agent/internal/google"
	logger "github.com/inference-gateway/google-calendar-agent/internal/logger"
)

// Version, AgentName and AgentDescription are injected at build time
// via `-ldflags "-X 'main.Version=...'"` (see Dockerfile). They default
// to the values declared in the ADL.
var (
	Version          = "0.5.1"
	AgentName        = "google-calendar-agent"
	AgentDescription = "A Google Calendar A2A agent for AI assistants to interact with Google Calendar"
)

// skillsDir is the directory the runtime scans for skill manifests at
// startup. Override with A2A_SKILLS_DIR.
const skillsDir = ".agents/skills"

// loadSkillsManifest walks the configured skills directory, reads each
// <skill>/SKILL.md, extracts the YAML frontmatter (name + description),
// and returns an `AVAILABLE SKILLS:` block to append to the system
// prompt. SKILL.md bodies are NOT inlined - the model must call the
// Read tool to load a skill's playbook on demand. Returns "" when the
// directory is missing or has no valid manifests.
func loadSkillsManifest(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	dirs := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, e.Name())
	}
	sort.Strings(dirs)

	type skillFrontmatter struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}

	var manifest strings.Builder
	for _, id := range dirs {
		path := filepath.Join(dir, id, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		fmBytes, ok := extractFrontmatter(data)
		if !ok {
			continue
		}
		var fm skillFrontmatter
		if err := yaml.Unmarshal(fmBytes, &fm); err != nil {
			continue
		}
		if fm.Name == "" || fm.Description == "" {
			continue
		}
		if manifest.Len() == 0 {
			manifest.WriteString("AVAILABLE SKILLS:\n")
			manifest.WriteString("Skills are reusable instructions for specific tasks. When a task matches a\n")
			manifest.WriteString("skill's description, read the SKILL.md file at the listed path using the Read\n")
			manifest.WriteString("tool, then follow its instructions.\n\n")
		}
		fmt.Fprintf(&manifest, "- %s: %s\n  Path: %s\n", fm.Name, fm.Description, path)
	}
	return manifest.String(), nil
}

// extractFrontmatter returns the bytes between the opening and closing
// `---` fences of a SKILL.md file (without including the fences
// themselves). The second return value is false when no frontmatter is
// found.
func extractFrontmatter(content []byte) ([]byte, bool) {
	bom := []byte{0xEF, 0xBB, 0xBF}
	buf := bytes.TrimPrefix(content, bom)
	buf = bytes.TrimLeft(buf, "\r\n\t ")
	if !bytes.HasPrefix(buf, []byte("---")) {
		return nil, false
	}
	rest := buf[3:]
	rest = bytes.TrimLeft(rest, "\r\n")
	idx := bytes.Index(rest, []byte("\n---"))
	if idx < 0 {
		return nil, false
	}
	return rest[:idx], true
}

// newRootCmd builds the top-level CLI for the agent binary. The
// generated binary is a real CLI: `<bin> --version`, `<bin> --help`,
// and `<bin> start` are all supported. Subcommands are added in
// dedicated constructors so they can be unit-tested in isolation.
func newRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:           AgentName,
		Short:         AgentDescription,
		Long:          AgentDescription + "\n\nThis is an A2A (Agent-to-Agent) protocol server. Use the `start` subcommand to run it.",
		Version:       Version,
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.AddCommand(newStartCmd())
	return root
}

// newStartCmd returns the `start` subcommand which boots the A2A
// server and blocks until SIGINT/SIGTERM.
func newStartCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start the A2A server",
		Long:  "Start the A2A server and block until SIGINT or SIGTERM is received.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStart(cmd.Context())
		},
	}
}

// runStart contains the original agent bootstrap. It is exported as a
// dedicated function so the cobra command stays a thin shell - easier
// to test, easier to embed.
func runStart(ctx context.Context) error {
	var cfg config.Config
	if err := envconfig.Process(ctx, &cfg); err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// AgentName and AgentVersion are build-time metadata (ldflags) that the ADK
	// deliberately does not map from the environment. Propagate them so the
	// OpenTelemetry resource carries service.name / service.version instead of
	// empty strings, and so any other consumer of cfg.A2A sees the real values.
	cfg.A2A.AgentName = AgentName
	cfg.A2A.AgentVersion = Version
	// The OpenTelemetry SDK settings are read as A2A_OTEL_* through the ADK's
	// A2A_-prefixed config (cfg.A2A.OTelConfig), so the single Process call above
	// already loaded them - no separate OTel pass is required.

	// Initialize logger
	l, err := logger.NewLogger(ctx, &cfg)
	if err != nil {
		return fmt.Errorf("failed to initialize logger: %w", err)
	}

	l.Info("starting "+AgentName+" agent", zap.String("version", Version), zap.Bool("debug", cfg.A2A.Debug))
	l.Debug("loaded configuration", zap.Any("config", cfg))

	resolvedSkillsDir := skillsDir
	if v := os.Getenv("A2A_SKILLS_DIR"); v != "" {
		resolvedSkillsDir = v
	}
	skillsPrompt, err := loadSkillsManifest(resolvedSkillsDir)
	if err != nil {
		l.Warn("failed to load skills manifest, continuing without them", zap.Error(err))
	} else if skillsPrompt != "" {
		l.Info("loaded skills manifest into system prompt", zap.String("dir", resolvedSkillsDir))
	}

	// Initialize services
	googleSvc, err := google.NewServiceFactory(l, &cfg)
	if err != nil {
		l.Error("failed to initialize google service", zap.Error(err))
		return fmt.Errorf("failed to initialize google service: %w", err)
	}

	// Create toolbox with default tools (like input_required, create_artifact etc)
	toolBox := server.NewDefaultToolBox(&cfg.A2A.AgentConfig.ToolBoxConfig)

	// Register Read built-in
	readTool, err := tools.NewReadTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Read tool: %w", err)
	}
	toolBox.AddTool(readTool)
	l.Info("registered built-in: Read")

	// Register list_calendar_events tool
	listCalendarEventsTool := tools.NewListCalendarEventsTool(l, googleSvc)
	toolBox.AddTool(listCalendarEventsTool)
	l.Info("registered tool: list_calendar_events (List upcoming events from Google Calendar)")

	// Register create_calendar_event tool
	createCalendarEventTool := tools.NewCreateCalendarEventTool(l, googleSvc)
	toolBox.AddTool(createCalendarEventTool)
	l.Info("registered tool: create_calendar_event (Create a new event in Google Calendar)")

	// Register update_calendar_event tool
	updateCalendarEventTool := tools.NewUpdateCalendarEventTool(l, googleSvc)
	toolBox.AddTool(updateCalendarEventTool)
	l.Info("registered tool: update_calendar_event (Update an existing event in Google Calendar)")

	// Register delete_calendar_event tool
	deleteCalendarEventTool := tools.NewDeleteCalendarEventTool(l, googleSvc)
	toolBox.AddTool(deleteCalendarEventTool)
	l.Info("registered tool: delete_calendar_event (Delete an event from Google Calendar)")

	// Register get_calendar_event tool
	getCalendarEventTool := tools.NewGetCalendarEventTool(l, googleSvc)
	toolBox.AddTool(getCalendarEventTool)
	l.Info("registered tool: get_calendar_event (Get details of a specific event from Google Calendar)")

	// Register find_available_time tool
	findAvailableTimeTool := tools.NewFindAvailableTimeTool(l, googleSvc)
	toolBox.AddTool(findAvailableTimeTool)
	l.Info("registered tool: find_available_time (Find available time slots in the calendar)")

	// Register check_conflicts tool
	checkConflictsTool := tools.NewCheckConflictsTool(l, googleSvc)
	toolBox.AddTool(checkConflictsTool)
	l.Info("registered tool: check_conflicts (Check for scheduling conflicts in the specified time range)")

	// Register get_current_datetime tool
	getCurrentDatetimeTool := tools.NewGetCurrentDatetimeTool(l)
	toolBox.AddTool(getCurrentDatetimeTool)
	l.Info("registered tool: get_current_datetime (Return the current date/time and the user's IANA timezone. Call this FIRST for any time-relative request (today, tomorrow, next Friday) before emitting RFC3339 timestamps to other calendar tools, so events land in the user's local timezone instead of an LLM-assumed default.)")

	llmClient, err := server.NewOpenAICompatibleLLMClient(&cfg.A2A.AgentConfig, l)
	if err != nil {
		return fmt.Errorf("failed to create LLM client: %w", err)
	}

	systemPrompt := `You are a Google Calendar AI agent specialized in calendar management and scheduling operations.

Your primary capabilities:
1. **Event Management**: Create, update, delete, and retrieve calendar events
2. **Scheduling Intelligence**: Find available time slots and check for conflicts
3. **Calendar Operations**: List events with flexible time ranges and search queries

Key features:
- Support for both mock mode (demo/testing) and production Google Calendar API
- RFC3339 timestamp handling for accurate scheduling
- Intelligent conflict detection and availability checking
- Attendee management and location tracking
- Comprehensive event search and filtering

When helping users:
- Always validate time formats and ranges
- Provide clear feedback on scheduling conflicts
- Suggest alternative time slots when conflicts are detected
- Handle both simple and complex scheduling scenarios
- Maintain data accuracy and consistency with Google Calendar

Time and timezone handling:
- For any time-relative request ("today", "tomorrow", "next Friday",
  "in 2 hours"), call the get_current_datetime tool FIRST to anchor
  the current time and the user's IANA timezone. Do not guess.
- Emit RFC3339 timestamps with the offset of the user's timezone
  (e.g. 2026-05-20T14:00:00+02:00 for CEST), not UTC and not a
  provider-default like Pacific Time.
- If the user names an explicit timezone, prefer that over the
  configured default.

Your responses should be accurate, helpful, and focused on calendar management tasks.
`
	if skillsPrompt != "" {
		systemPrompt = systemPrompt + "\n\n" + skillsPrompt
	}

	agent, err := server.NewAgentBuilder(l).
		WithConfig(&cfg.A2A.AgentConfig).
		WithLLMClient(llmClient).
		WithToolBox(toolBox).
		WithMaxChatCompletion(cfg.A2A.AgentConfig.MaxChatCompletionIterations).
		WithSystemPrompt(systemPrompt).
		Build()
	if err != nil {
		return fmt.Errorf("failed to create agent: %w", err)
	}

	a2aServer, err := server.NewA2AServerBuilder(cfg.A2A, l).
		WithAgent(agent).
		WithAgentCardFromFile(".well-known/agent-card.json", map[string]any{
			"name":        AgentName,
			"version":     Version,
			"description": AgentDescription,
			"url":         cfg.A2A.AgentURL,
		}).
		WithDefaultBackgroundTaskHandler().
		WithDefaultStreamingTaskHandler().
		Build()
	if err != nil {
		return fmt.Errorf("failed to create A2A server: %w", err)
	}

	go func() {
		l.Info("starting A2A server", zap.String("port", cfg.A2A.ServerConfig.Port))
		if err := a2aServer.Start(ctx); err != nil {
			l.Fatal("server failed to start", zap.Error(err))
		}
	}()

	l.Info("google-calendar-agent agent running successfully",
		zap.String("port", cfg.A2A.ServerConfig.Port))

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	l.Info("shutdown signal received, gracefully stopping server...")
	a2aServer.Stop(ctx)
	l.Info("google-calendar-agent agent stopped")
	return nil
}

func main() {
	ctx := context.Background()
	if err := newRootCmd().ExecuteContext(ctx); err != nil {
		log.Fatal(err)
	}
}
