---
version: "3"

tasks:
  default:
    desc: "Show help information"
    cmds:
      - task --list

  a2a:download:schema:
    desc: "Download the latest A2A schema and convert to YAML"
    cmds:
      - curl -o a2a/a2a-schema.json https://raw.githubusercontent.com/google-a2a/A2A/main/specification/json/a2a.json
      - |
        echo "Converting A2A JSON schema to YAML format"
        NODE_PATH=/usr/lib/node_modules node -e "
          const fs = require('fs');
          const yaml = require('js-yaml');
          const json = JSON.parse(fs.readFileSync('a2a/a2a-schema.json', 'utf8'));
          fs.writeFileSync('a2a/a2a-schema.yaml', yaml.dump(json, {lineWidth: -1}));
        "

  generate:
    desc: "Generate Go code from the official A2A JSON RPC Schema"
    cmds:
      - echo "Generating Go code from JSON RPC Schema..."
      - go run cmd/codegen/main.go -output a2a/generated_types.go
      - go generate ./...

  tidy:
    desc: "Run go mod tidy to clean up dependencies"
    cmds:
      - echo "Running go mod tidy..."
      - go mod tidy

  lint:
    desc: "Run linters on the codebase"
    cmds:
      - echo "Running linters..."
      - golangci-lint run

  build:
    desc: "Build the project with version information"
    cmds:
      - echo "Building the project..."
      - |
        VERSION=$(git describe --tags --always --dirty)
        COMMIT=$(git rev-parse HEAD)
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        go build -ldflags "-X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}" -o bin/google-calendar-agent cmd/google-calendar-agent/main.go

  build:dev:
    desc: "Build the project for development (no version information)"
    cmds:
      - echo "Building the project for development..."
      - go build -o bin/google-calendar-agent cmd/google-calendar-agent/main.go

  build:docker:
    desc: "Build the Docker image with version information"
    cmds:
      - echo "Building Docker image..."
      - |
        VERSION=$(git describe --tags --always --dirty)
        COMMIT=$(git rev-parse HEAD)
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        docker build \
          --build-arg VERSION="${VERSION}" \
          --build-arg COMMIT="${COMMIT}" \
          --build-arg DATE="${DATE}" \
          -t google-calendar-agent:latest \
          -t google-calendar-agent:${VERSION} \
          .

  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - go test ./...

  clean:
    desc: "Clean up build artifacts"
    cmds:
      - echo "Cleaning up..."
      - rm -rf bin/
