// Code generated by ADL CLI v0.23.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Custom configuration sections
	Google         GoogleConfig         `env:",prefix=GOOGLE_"`
	GoogleCalendar GoogleCalendarConfig `env:",prefix=GOOGLE_CALENDAR_"`
}

// GoogleConfig represents the google configuration
type GoogleConfig struct {
	CredentialsPath    string `env:"CREDENTIALS_PATH"`
	ServiceAccountJSON string `env:"SERVICE_ACCOUNT_JSON"`
}

// GoogleCalendarConfig represents the googleCalendar configuration
type GoogleCalendarConfig struct {
	ID       string `env:"ID,default=primary"`
	MockMode bool   `env:"MOCK_MODE"`
	Timezone string `env:"TIMEZONE,default=UTC"`
}
