// Code generated by ADL CLI v0.20.7 on 2025-09-17 17:45:54. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Custom configuration sections
	Google GoogleConfig `env:",prefix=GOOGLE_"`
}

// GoogleConfig represents the google configuration
type GoogleConfig struct {
	CalendarID         string `env:"CALENDAR_ID,default=primary"`
	CredentialsPath    string `env:"CREDENTIALS_PATH"`
	MockMode           bool   `env:"MOCK_MODE"`
	ServiceAccountJSON string `env:"SERVICE_ACCOUNT_JSON"`
}
